config/routes.rb
Rails.application.routes.draw do
  root                    to: 'home#index'
  get  'welcome',          to: 'session#welcome'
  get  'welcome_callback', to: 'session#welcome_callback'
  get  'logout',           to: 'session#logout'

  get  'vote',             to: 'contest#round'
  get  'results',          to: 'contest#scores'
  get  'profile',          to: 'people#profile'

  get  'dev_login',        to: 'session#dev_login'
  post 'do_batch_import', to: 'admin#do_batch_import'

  match ':controller(/:action(/:id))(.:format)', via: [:get, :post]

end

app/models/concerns/people/image.rb
module People::Image
  extend ActiveSupport::Concern

  included do
    # before_save :serialize_image_hash
    before_validation :google_image
  end

  def set_image(image_hash)
    self.image_json = image_hash.to_json
    self.score = Person::DEFAULT_SCORE
    self.imaged = Person.image_from_hash(image_hash, Person::DEFAULT_WIDTH, fix: true)
  end

  def unset_image
    self.imaged = nil
    self.image_hash = nil
    self.score = nil
  end

  def image_hash
    @image_hash ||= Oj.load(image_json)
  end

  def serialize_image_hash
    self.image_json = Oj.dump(@image_hash) if @image_hash
  end

  def image(width = nil)
    return imaged unless width
    self.class.image_from_hash(image_hash, width)
  end

  def google_image
    return unless imaged_changed?
    s = ImageSearcher.new(imaged)
    return if (guess = s.guess).blank? && s.matches <= Person::MANY_GOOGLIES
    errors.add :imaged, "#{guess} #{I18n.t 'image.cant_be_set'}"
  end

  module ClassMethods
    SIZES_MAPPING = { 's' => 75, 'm' => 130, 'x' => 604, 'o' => 130, 'p' => 200, 'q' => 320, 'y' => 807, 'z' => 1280, 'w' => 2560 }

    def image_from_hash(hash, width, fix: false)
      attempt_to_fix_hash(hash) if fix
      sizes = hash['sizes']
      sz = sizes.min_by { |x| (x['width'] - width).abs }
      return sz['src'] if sz['width'] != 0
      return bullshit_sizes(sizes)
    end

    def attempt_to_fix_hash(hash)
      sizes = hash['sizes']
      return unless sizes.any? { |s| s['width'] == 0 }
      broken_cnt = 0
      sizes.each do |s|
        width = SIZES_MAPPING[s['type']]
        s['width'] = width || 450
        broken_cnt += 1 if width.nil?
      end
      sizes.last['width'] = 500 if broken_cnt == sizes.size
    end

    def bullshit_sizes(sizes)
      sizes.find { |s| s['type'] =~ /x|y/ }['src'] ||
      sizes.find { |s| s['type'] =~ 'q' }['src'] ||
      sizes.last['src'] ||
      (raise 'Bullshit image')
    end
  end
end

app/models/concerns/people/round.rb
module People::Round
  extend ActiveSupport::Concern

  def rounds_save(cnt)
    return unless cnt % 10 == 0
    self.update(rounds: cnt)
  end

  def load_pair(pair_ids)
    way = pair_ids.first > pair_ids.last ? 'ASC' : 'DESC'
    pair = Person.where(id: pair_ids).order('people.id ' + way).all.to_a
    raise 'Could not load pair' unless pair.size == 2
    pair
  end

  module ClassMethods
    def random_pair
      pair = Person.where('imaged IS NOT NULL').order('random()').limit(2)
      raise 'Need at least 2 contestants' unless pair.size == 2
      pair
    end
  end
end

app/models/concerns/people/score.rb
module People::Score
  extend ActiveSupport::Concern

  def beats(other)
    Person.transaction do
      self.update_columns( score: score_change(self.score,  other.score, 1.0))
      other.update_columns(score: score_change(other.score, self.score,  0.0))
    end
  end

  private

  def score_change(a, b, s)
    a + 400.0 * (s - (1.0 / (1.0 + 10.0**((b - a) / 400.0))))
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  include People::Score, People::Round, People::Image

  VK_PERMITTED_FIELDS = [
    :uid, :first_name, :last_name, :sex, :university, :university_name,
    :activities, :interests, :music, :movies, :tv, :books, :games, :about, :quotes
  ].freeze
  VK_REQUEST_FIELDS = (VK_PERMITTED_FIELDS + [:education]).freeze
  DEFAULT_WIDTH = 500
  DEFAULT_SCORE = 400
  MANY_GOOGLIES = 50

  validates :uid, :first_name, :last_name, :sex, presence: true
  validates_uniqueness_of :uid

  def self.vk(mash)
    hash = mash.to_hash.symbolize_keys.slice(*VK_PERMITTED_FIELDS)
    person = where(uid: mash.uid).first
    if person.present?
      person.update_attributes(hash)
      return person
    else
      person = create(hash)
      person.updated_at = nil
      return person
    end
  end

  def in?
    imaged.present?
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  def profile
    @profile = Person.find(params[:id])
  end

  def show
  end

  def edit
  end

  def new
  end

  def create
    if Person.new(person_params).save
      redirect_to @person, notice: 'Person was successfully created.' 
    else
      render :new
    end
  end

  def update
    if @person.update(person_params)
      redirect_to @person, notice: 'Person was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @person.destroy
    redirect_to people_url, notice: 'Person was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:image, :name, :university, :score, :rounds, :quotes)
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :university %><br>
    <%= f.text_field :university %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>
  <div class="field">
    <%= f.label :rounds %><br>
    <%= f.number_field :rounds %>
  </div>
  <div class="field">
    <%= f.label :quotes %><br>
    <%= f.text_area :quotes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/callback.html.erb
<%= @person.errors.inspect %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/info.html.erb
<table style="width:100%" border="1">
  <tr>
    <td>User</td>
    <td><%= @user.inspect %></td>
  </tr>
  <tr>
    <td>Frineds</td>
    <td><%= @friends.inspect %></td>
  </tr>
  <tr>
    <td>groups</td>
    <td><%= @groups.inspect %></td>
  </tr>
  <tr>
    <td>photos</td>
    <td>
        <table>
          <% @photos.each do |photo| %>
            <td><%= image_tag photo.src_small %></td>
            <td><%= image_tag photo.src %></td>
            <td><%= image_tag photo.src_big %></td>
            <td><%= image_tag photo.src_xbig %></td>
          <% end %>
        </table>
    </td>
  </tr>
</table>

app/views/people/profile.html.erb
<%= @profile.first_name %>
<%= @profile.image_hash %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @person.image %>
</p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>University:</strong>
  <%= @person.university %>
</p>

<p>
  <strong>Score:</strong>
  <%= @person.score %>
</p>

<p>
  <strong>Rounds:</strong>
  <%= @person.rounds %>
</p>

<p>
  <strong>Quotes:</strong>
  <%= @person.quotes %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/people/vk_login.html.erb
<h1>LOGIN VK BIATCH</h1>
<%= link_to "'click'", @vk_url %>