config/routes.rb
Rails.application.routes.draw do
  root                    to: 'home#index'
  get  'welcome',          to: 'session#welcome'
  get  'welcome_callback', to: 'session#welcome_callback'
  get  'logout',           to: 'session#logout'

  get  'vote',             to: 'contest#round'
  get  'results',          to: 'contest#scores'
  get  'profile',          to: 'people#profile'

  get  'dev_login',        to: 'session#dev_login'
  post 'do_batch_import', to: 'admin#do_batch_import'

  match ':controller(/:action(/:id))(.:format)', via: [:get, :post]

end

app/views/admin/batch_import.html.erb
<div>
    <%= form_tag do_batch_import_path do %>
        <%= text_area_tag(:uids) %><br>
        <%= submit_tag 'Batch import ids' %>
    <% end %>
</div>

app/views/admin/chart.html.erb
<% @header = 'Charts' %>

<div id="canvasd" width="800" height="400"></div>

<%= form_tag({ controller: :admin, action: :load_chart }, { remote: true }) do %>
    <%= text_field_tag :start, @start, { 'data-provide' => 'datepicker'} %>
    <%= text_field_tag :end, @end, { 'data-provide' => 'datepicker'} %>
    <%= submit_tag 'load' %>
<% end %>

app/views/admin/do_batch_import.html.erb
<h1 class="page-header">Added <%= @people.size %> people</h1>

<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th>Login</th>
    <th>University</th>
    <th>Score</th>
    <th>Rounds</th>
  </tr>
  </thead>

  <tbody>
  <% @people.each do |person| %>
      <tr>
        <td><%= "#{person.first_name} #{person.last_name}" %></td>
        <td><%= link_to '<login>', dev_login_path(id: person.id) %></td>
        <td><%= person.university %></td>
        <td><%= person.score %></td>
        <td><%= person.rounds %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/admin/load_chart.js.erb
data = {
    labels : <%= @qlength.inspect %>,
    datasets : [
        {
            fillColor : "rgba(220,220,220,0.5)",
            strokeColor : "rgba(220,220,220,1)",
            pointColor : "rgba(220,220,220,1)",
            pointStrokeColor : "#fff",
            data : <%= @qlength.inspect %>
        }
    ]
};

$("#canvasd").empty();
$("#canvasd").append('<canvas id="canvas"></canvas>');


chart = new Chart($("#canvas").get(0).getContext("2d")).Line(data);