config/routes.rb
Rails.application.routes.draw do
  root                    to: 'home#index'
  get  'welcome',          to: 'session#welcome'
  get  'welcome_callback', to: 'session#welcome_callback'
  get  'logout',           to: 'session#logout'

  get  'vote',             to: 'contest#round'
  get  'results',          to: 'contest#scores'
  get  'profile',          to: 'people#profile'

  get  'dev_login',        to: 'session#dev_login'
  post 'do_batch_import', to: 'admin#do_batch_import'

  match ':controller(/:action(/:id))(.:format)', via: [:get, :post]

end

app/views/layouts/_header_buttons.erb
<div class='btn-toolbar pull-right'>
  <div class='btn-group'>
    <%= link_to person.first_name,     root_path,    type: 'button', class: "btn btn-primary #{'active' if current_page?(root_path) }" %>
    <%= link_to (t 'navbar.vote'), vote_path,    type: 'button', class: "btn btn-primary #{'active' if current_page?(vote_path) }" %>
    <%= link_to (t 'navbar.top'),  results_path, type: 'button', class: "btn btn-primary #{'active' if current_page?(results_path) }" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Contest" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="container">
      <div class="row content-row">
        <div class="col-lg-12">
          <% if lin? %>
              <div class="page-header">
                <div class='btn-toolbar pull-right'>
                  <div class='btn-group'>
                    <%= link_to person.first_name, root_path,    type: 'button', class: "btn btn-primary #{'active' if current_page?(root_path) }" %>
                    <%= link_to (t 'navbar.vote'), vote_path,    type: 'button', class: "btn btn-primary #{'active' if current_page?(vote_path) }" %>
                    <%= link_to (t 'navbar.top'),  results_path, type: 'button', class: "btn btn-primary #{'active' if current_page?(results_path) }" %>
                  </div>
                </div>
                <h3><%= @header.html_safe %></h3>
              </div>
          <% end %>
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer>
        <!--<p>&copy; Company 2015</p>-->
      </footer>

    </div> <!-- /container -->

  </body>
</html>